version: '3.8'

services:
  db1:
    image: postgres:13
    environment:
      POSTGRES_DB: neonumy
      POSTGRES_USER: neonumy
      POSTGRES_PASSWORD: neonumy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web1:
    build: .
    command: python app.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db1
    environment:
      - DATABASE_URL=postgresql://neonumy:neonumy@db1:5432/neonumy


volumes:
  postgres_data: